
package com.agent.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightDaoImpl", targetNamespace = "http://dao.agent.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightDaoImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.agent.dao.Flight
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlight", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetFlight")
    @ResponseWrapper(localName = "getFlightResponse", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetFlightResponse")
    @Action(input = "http://dao.agent.com/FlightDaoImpl/getFlightRequest", output = "http://dao.agent.com/FlightDaoImpl/getFlightResponse")
    public Flight getFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.agent.dao.Flight>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFlights", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetAllFlights")
    @ResponseWrapper(localName = "getAllFlightsResponse", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetAllFlightsResponse")
    @Action(input = "http://dao.agent.com/FlightDaoImpl/getAllFlightsRequest", output = "http://dao.agent.com/FlightDaoImpl/getAllFlightsResponse")
    public List<Flight> getAllFlights();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.agent.dao.Flight>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlights", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetFlights")
    @ResponseWrapper(localName = "getFlightsResponse", targetNamespace = "http://dao.agent.com/", className = "com.agent.dao.GetFlightsResponse")
    @Action(input = "http://dao.agent.com/FlightDaoImpl/getFlightsRequest", output = "http://dao.agent.com/FlightDaoImpl/getFlightsResponse")
    public List<Flight> getFlights(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
