
package com.agent.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TicketDaoImplService", targetNamespace = "http://dao.agent.com/", wsdlLocation = "http://localhost:8081/Service/TicketDao?wsdl")
public class TicketDaoImplService
    extends Service
{

    private final static URL TICKETDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TICKETDAOIMPLSERVICE_EXCEPTION;
    private final static QName TICKETDAOIMPLSERVICE_QNAME = new QName("http://dao.agent.com/", "TicketDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Service/TicketDao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TICKETDAOIMPLSERVICE_WSDL_LOCATION = url;
        TICKETDAOIMPLSERVICE_EXCEPTION = e;
    }

    public TicketDaoImplService() {
        super(__getWsdlLocation(), TICKETDAOIMPLSERVICE_QNAME);
    }

    public TicketDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TICKETDAOIMPLSERVICE_QNAME, features);
    }

    public TicketDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, TICKETDAOIMPLSERVICE_QNAME);
    }

    public TicketDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TICKETDAOIMPLSERVICE_QNAME, features);
    }

    public TicketDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TicketDaoImpl
     */
    @WebEndpoint(name = "TicketDaoImplPort")
    public TicketDaoImpl getTicketDaoImplPort() {
        return super.getPort(new QName("http://dao.agent.com/", "TicketDaoImplPort"), TicketDaoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketDaoImpl
     */
    @WebEndpoint(name = "TicketDaoImplPort")
    public TicketDaoImpl getTicketDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.agent.com/", "TicketDaoImplPort"), TicketDaoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TICKETDAOIMPLSERVICE_EXCEPTION!= null) {
            throw TICKETDAOIMPLSERVICE_EXCEPTION;
        }
        return TICKETDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
