
package com.bank.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountDaoImpl", targetNamespace = "http://dao.bank.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountDaoImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAccountBalance", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.UpdateAccountBalance")
    @ResponseWrapper(localName = "updateAccountBalanceResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.UpdateAccountBalanceResponse")
    @Action(input = "http://dao.bank.com/AccountDaoImpl/updateAccountBalanceRequest", output = "http://dao.bank.com/AccountDaoImpl/updateAccountBalanceResponse")
    public boolean updateAccountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalance", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountBalance")
    @ResponseWrapper(localName = "getAccountBalanceResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountBalanceResponse")
    @Action(input = "http://dao.bank.com/AccountDaoImpl/getAccountBalanceRequest", output = "http://dao.bank.com/AccountDaoImpl/getAccountBalanceResponse")
    public int getAccountBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bank.dao.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountsByName", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountsByName")
    @ResponseWrapper(localName = "getAccountsByNameResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountsByNameResponse")
    @Action(input = "http://dao.bank.com/AccountDaoImpl/getAccountsByNameRequest", output = "http://dao.bank.com/AccountDaoImpl/getAccountsByNameResponse")
    public List<Account> getAccountsByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bank.dao.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountResponse")
    @Action(input = "http://dao.bank.com/AccountDaoImpl/getAccountRequest", output = "http://dao.bank.com/AccountDaoImpl/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bank.dao.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAccounts", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAllAccounts")
    @ResponseWrapper(localName = "getAllAccountsResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAllAccountsResponse")
    @Action(input = "http://dao.bank.com/AccountDaoImpl/getAllAccountsRequest", output = "http://dao.bank.com/AccountDaoImpl/getAllAccountsResponse")
    public List<Account> getAllAccounts();

}
