
package com.bank.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountDaoImplService", targetNamespace = "http://dao.bank.com/", wsdlLocation = "http://localhost:10002/Service/AccountDao?wsdl")
public class AccountDaoImplService
    extends Service
{

    private final static URL ACCOUNTDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTDAOIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTDAOIMPLSERVICE_QNAME = new QName("http://dao.bank.com/", "AccountDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10002/Service/AccountDao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTDAOIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTDAOIMPLSERVICE_EXCEPTION = e;
    }

    public AccountDaoImplService() {
        super(__getWsdlLocation(), ACCOUNTDAOIMPLSERVICE_QNAME);
    }

    public AccountDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTDAOIMPLSERVICE_QNAME, features);
    }

    public AccountDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTDAOIMPLSERVICE_QNAME);
    }

    public AccountDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTDAOIMPLSERVICE_QNAME, features);
    }

    public AccountDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountDaoImpl
     */
    @WebEndpoint(name = "AccountDaoImplPort")
    public AccountDaoImpl getAccountDaoImplPort() {
        return super.getPort(new QName("http://dao.bank.com/", "AccountDaoImplPort"), AccountDaoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountDaoImpl
     */
    @WebEndpoint(name = "AccountDaoImplPort")
    public AccountDaoImpl getAccountDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.bank.com/", "AccountDaoImplPort"), AccountDaoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTDAOIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTDAOIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
