
package com.bank.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BillDaoImplService", targetNamespace = "http://dao.bank.com/", wsdlLocation = "http://localhost:10002/Service/BillDao?wsdl")
public class BillDaoImplService
    extends Service
{

    private final static URL BILLDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BILLDAOIMPLSERVICE_EXCEPTION;
    private final static QName BILLDAOIMPLSERVICE_QNAME = new QName("http://dao.bank.com/", "BillDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10002/Service/BillDao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLDAOIMPLSERVICE_WSDL_LOCATION = url;
        BILLDAOIMPLSERVICE_EXCEPTION = e;
    }

    public BillDaoImplService() {
        super(__getWsdlLocation(), BILLDAOIMPLSERVICE_QNAME);
    }

    public BillDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLDAOIMPLSERVICE_QNAME, features);
    }

    public BillDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, BILLDAOIMPLSERVICE_QNAME);
    }

    public BillDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLDAOIMPLSERVICE_QNAME, features);
    }

    public BillDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillDaoImpl
     */
    @WebEndpoint(name = "BillDaoImplPort")
    public BillDaoImpl getBillDaoImplPort() {
        return super.getPort(new QName("http://dao.bank.com/", "BillDaoImplPort"), BillDaoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillDaoImpl
     */
    @WebEndpoint(name = "BillDaoImplPort")
    public BillDaoImpl getBillDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.bank.com/", "BillDaoImplPort"), BillDaoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLDAOIMPLSERVICE_EXCEPTION!= null) {
            throw BILLDAOIMPLSERVICE_EXCEPTION;
        }
        return BILLDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
