
package com.bank.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BillDaoImpl", targetNamespace = "http://dao.bank.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BillDaoImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "charge", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.Charge")
    @ResponseWrapper(localName = "chargeResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.ChargeResponse")
    @Action(input = "http://dao.bank.com/BillDaoImpl/chargeRequest", output = "http://dao.bank.com/BillDaoImpl/chargeResponse")
    public int charge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        XMLGregorianCalendar arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPassword", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.CheckPassword")
    @ResponseWrapper(localName = "checkPasswordResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.CheckPasswordResponse")
    @Action(input = "http://dao.bank.com/BillDaoImpl/checkPasswordRequest", output = "http://dao.bank.com/BillDaoImpl/checkPasswordResponse")
    public int checkPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bank.dao.Bill>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBills", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountBills")
    @ResponseWrapper(localName = "getAccountBillsResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAccountBillsResponse")
    @Action(input = "http://dao.bank.com/BillDaoImpl/getAccountBillsRequest", output = "http://dao.bank.com/BillDaoImpl/getAccountBillsResponse")
    public List<Bill> getAccountBills(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bank.dao.Bill>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBills", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAllBills")
    @ResponseWrapper(localName = "getAllBillsResponse", targetNamespace = "http://dao.bank.com/", className = "com.bank.dao.GetAllBillsResponse")
    @Action(input = "http://dao.bank.com/BillDaoImpl/getAllBillsRequest", output = "http://dao.bank.com/BillDaoImpl/getAllBillsResponse")
    public List<Bill> getAllBills();

}
